"""Hypnos — a curated, citation-backed, tier-annotated dataset of anesthetic and
perioperative PK/PD models, with envelope-aware forward simulation and exports
into the standard pharmacometric formats.

NOT a clinical decision-support tool. NOT a TCI pump driver. NOT a dosing
calculator. For research, method development, education, and simulation only.
See spec §10.
"""
from __future__ import annotations

__version__ = "0.9.0"

CLINICAL_USE = "PROHIBITED — research/education/simulation only"

from .analysis import (  # noqa: E402
    CohortValidation,
    DecrementTime,
    Leaderboard,
    LeaderboardEntry,
    PeakEffect,
    PopulationPerformance,
    SubjectRecord,
    VarvelResult,
    cross_model_leaderboard,
    decrement_time,
    partition_by_envelope,
    performance_error,
    pooled_performance,
    subjects_from_cohort_self_consistency,
    subjects_from_csv,
    subjects_from_vitaldb,
    time_to_peak_effect,
    validate_against_cohort,
    varvel_metrics,
)
from .covariates import (  # noqa: E402
    EquationResult,
    covariate_layer_tier,
    evaluate as evaluate_covariate,
    has_covariate_distribution,
    point_patient,
    sample_covariate_vector,
)
from .filter import performance_table, select, summary  # noqa: E402
from .inhalational import (  # noqa: E402
    MacResult,
    WashinResult,
    WashoutResult,
    mac,
    washin,
    washin_comparison,
    washout,
    washout_comparison,
)
from .load import Dataset, load  # noqa: E402
from .developmental import (  # noqa: E402
    allometric_scale,
    apply_developmental,
    linear_per_kg_scale,
    maturation_factor,
)
from .models import (  # noqa: E402
    CovariateModel,
    DerivedInput,
    DevelopmentalModel,
    EstimateCovariance,
    EstimationUncertainty,
    MaturationModel,
    Model,
    OmegaBlock,
    Parameter,
    ParameterVariability,
    PharmacogenomicModifier,
    PharmacogenomicSafetyFlag,
    ResidualError,
    SizeModel,
    ToxicityThreshold,
    worst_tier,
)
from .pharmacogenomics import (  # noqa: E402
    PgxFinding,
    PgxOverlay,
    pgx_overlay,
)
from .simulate import (  # noqa: E402
    Comparison,
    CovariateDivergence,
    DevelopmentalExtrapolation,
    DevelopmentalOverlay,
    EquationCurve,
    InteractionResult,
    SimulationResult,
    compare,
    covariate_divergence,
    developmental_overlay,
    simulate,
    simulate_interaction,
)
from .validate import assert_valid, validate_dataset  # noqa: E402
from .verification import (  # noqa: E402
    ModelVerification,
    checklist_markdown,
    model_verification,
    next_to_verify,
    verification_summary,
)

__all__ = [
    "__version__",
    "CLINICAL_USE",
    "load",
    "Dataset",
    "Model",
    "Parameter",
    "ParameterVariability",
    "ResidualError",
    "OmegaBlock",
    "EstimationUncertainty",
    "EstimateCovariance",
    "ToxicityThreshold",
    "CovariateModel",
    "DerivedInput",
    "evaluate_covariate",
    "covariate_layer_tier",
    "sample_covariate_vector",
    "point_patient",
    "has_covariate_distribution",
    "EquationResult",
    "select",
    "summary",
    "performance_table",
    "simulate",
    "compare",
    "covariate_divergence",
    "developmental_overlay",
    "simulate_interaction",
    "Comparison",
    "CovariateDivergence",
    "DevelopmentalExtrapolation",
    "DevelopmentalOverlay",
    "EquationCurve",
    "SimulationResult",
    "InteractionResult",
    "DevelopmentalModel",
    "SizeModel",
    "MaturationModel",
    "allometric_scale",
    "maturation_factor",
    "apply_developmental",
    "linear_per_kg_scale",
    "PharmacogenomicModifier",
    "PharmacogenomicSafetyFlag",
    "pgx_overlay",
    "PgxOverlay",
    "PgxFinding",
    "mac",
    "MacResult",
    "washin",
    "washin_comparison",
    "WashinResult",
    "washout",
    "washout_comparison",
    "WashoutResult",
    "time_to_peak_effect",
    "PeakEffect",
    "decrement_time",
    "DecrementTime",
    "performance_error",
    "varvel_metrics",
    "pooled_performance",
    "validate_against_cohort",
    "cross_model_leaderboard",
    "partition_by_envelope",
    "Leaderboard",
    "LeaderboardEntry",
    "subjects_from_csv",
    "subjects_from_cohort_self_consistency",
    "subjects_from_vitaldb",
    "VarvelResult",
    "PopulationPerformance",
    "SubjectRecord",
    "CohortValidation",
    "validate_dataset",
    "assert_valid",
    "worst_tier",
    "verification_summary",
    "model_verification",
    "next_to_verify",
    "checklist_markdown",
    "ModelVerification",
]
